PizzaRe-up/Form1.Designer.cs
PizzaRe-up/Form1.cs
PizzaRe-up/Program.cs

Renaming elements.

---

PizzaRe-up/Edit.Designer.cs
PizzaRe-up/Edit.cs
PizzaRe-up/Edit.resx
PizzaRe-up/Form1.Designer.cs
PizzaRe-up/Form1.cs

Added edit form

---

PizzaRe-up/Pizza.cs

Setting up the pizza elements.

---

PizzaRe-up/Pizza.cs

Made all the ingredients into one element.

---

PizzaRe-up/Form1.Designer.cs

Added crust selections

---

PizzaRe-up/Form1.Designer.cs
PizzaRe-up/Form1.cs
PizzaRe-up/Preset.Designer.cs
PizzaRe-up/Preset.cs

Preset button opens form and cancel button closes form

---

PizzaRe-up/Form1.Designer.cs
PizzaRe-up/Preset.cs

Preset cancel button closes form and added ingredients groupbox

---

PizzaRe-up/PizzaContext.cs

added PizzaContext class

---

PizzaRe-up/Pizza.cs

add key annotation to pizza class

---

PizzaRe-up/Pizza.cs

Added crust and size

---

PizzaRe-up/Pizza.cs

Finished constructor and added PizzaId field in pizza class

---

PizzaRe-up/Migrations/20230209041207_Initial.Designer.cs
PizzaRe-up/Migrations/20230209041207_Initial.cs
PizzaRe-up/PizzaContext.cs

Changed DB name and primary key

---

PizzaRe-up/Form1.Designer.cs
PizzaRe-up/Form1.cs
PizzaRe-up/Pizza.cs

Added to the database.

---

PizzaRe-up/Pizza.cs

Added the customer name to the Pizza class.

---

PizzaRe-up/Form1.Designer.cs

Added textbox for entering name for order

---

PizzaRe-up/Form1.cs
PizzaRe-up/PizzaContext.cs

Resolves #57 
Resolves #61
Resolves #60 
Resolves #64
Resolves #65

Added local functions for submit button code

---

PizzaRe-up/Form1.cs
PizzaRe-up/PizzaContext.cs

Name field gets added to pizza object

---

PizzaRe-up/Pizza.cs
PizzaRe-up/PizzaContext.cs

Put the required documentation inside the Pizza class.

---

PizzaRe-up/Pizza.cs

Added ToString for pizza class

---

PizzaRe-up/Form1.cs

Made size capital letters
